### ISSUE TITLE
Crashed after receiving the Postmortal advancement when being blasted by a warden

### ISSUE THREAD

**Issue by Jawzper** [alessandrv/alessandrv-enchantments#10]
Been playing around with modding Decked Out 2. 

Since this mod is mentioned in the error log, I thought I should post this here. I was wearing headgear with Spotter enchantment at the time, in case that helps.

```[08/01/2024 18:08:49 pm] [Server thread/INFO] **MINECRAFTUSERNAME** has reached the goal [Postmortal]
[08/01/2024 18:08:49 pm] [Render thread/INFO] [CHAT] **MINECRAFTUSERNAME** has reached the goal [Postmortal]
[08/01/2024 18:08:49 pm] 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:901)
[08/01/2024 18:08:49 pm] 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1132.method_3748(class_1132.java:105)
[08/01/2024 18:08:49 pm] 	at net.minecraft.server.MinecraftServer.handler$zje000$carpet$modifiedRunLoop(MinecraftServer.java:8442)
[08/01/2024 18:08:49 pm] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
[08/01/2024 18:08:49 pm] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[08/01/2024 18:08:49 pm] 	at java.base/java.lang.Thread.run(Thread.java:833)
[08/01/2024 18:08:49 pm] Caused by: java.util.ConcurrentModificationException
[08/01/2024 18:08:49 pm] 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
[08/01/2024 18:08:49 pm] 	at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1625)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.handler$zze000$alessandrvenchantments$clearStatusEffects(class_1309.java:4645)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.method_6012(class_1309.java)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.method_6095(class_1309.java:1281)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.method_5643(class_1309.java:1217)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1657.method_5643(class_1657.java:928)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3222.method_5643(class_3222.java:732)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_7396.method_43265(class_7396.java:87)
[08/01/2024 18:08:49 pm] 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_7396.method_43268(class_7396.java:74)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_7396.method_18924(class_7396.java:19)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_4097.method_18923(class_4097.java:66)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_4095.method_19545(class_4095.java:548)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_4095.method_19542(class_4095.java:493)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_7260.method_5958(class_7260.java:311)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1308.method_6023(class_1308.java:788)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.method_6007(class_1309.java:2673)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1308.method_6007(class_1308.java:550)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1588.method_6007(class_1588.java:44)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1308.method_5773(class_1308.java:351)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_7260.method_5773(class_7260.java:278)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3218.track(class_3218.java:8754)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3218.redirect$deo000$observable$onTickNonPassenger(class_3218.java:8770)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3218.method_18762(class_3218.java:739)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1937.method_18472(class_1937.java:480)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3218.method_31420(class_3218.java:385)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3218.method_18765(class_3218.java:353)
[08/01/2024 18:08:49 pm] 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
[08/01/2024 18:08:49 pm] 	... 6 more
[08/01/2024 18:08:49 pm] [Server thread/ERROR] Encountered an unexpected exception
[08/01/2024 18:08:49 pm] [Server thread/ERROR] This crash report has been saved to: **USERSDIR**\instances\HermitcraftS9WorldDownload\crash-reports\crash-2024-01-08_18.08.49-server.txt
[08/01/2024 18:08:49 pm] ---- Minecraft Crash Report ----
[08/01/2024 18:08:49 pm] // Hi. I'm Minecraft, and I'm a crashaholic.
[08/01/2024 18:08:49 pm] 
[08/01/2024 18:08:49 pm] Time: 2024-01-08 18:08:49
[08/01/2024 18:08:49 pm] Description: Ticking entity
[08/01/2024 18:08:49 pm] 
[08/01/2024 18:08:49 pm] java.util.ConcurrentModificationException
[08/01/2024 18:08:49 pm] 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
[08/01/2024 18:08:49 pm] 	at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1625)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.handler$zze000$alessandrvenchantments$clearStatusEffects(class_1309.java:4645)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.method_6012(class_1309.java)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.method_6095(class_1309.java:1281)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.method_5643(class_1309.java:1217)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1657.method_5643(class_1657.java:928)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3222.method_5643(class_3222.java:732)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_7396.method_43265(class_7396.java:87)
[08/01/2024 18:08:49 pm] 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_7396.method_43268(class_7396.java:74)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_7396.method_18924(class_7396.java:19)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_4097.method_18923(class_4097.java:66)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_4095.method_19545(class_4095.java:548)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_4095.method_19542(class_4095.java:493)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_7260.method_5958(class_7260.java:311)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1308.method_6023(class_1308.java:788)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.method_6007(class_1309.java:2673)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1308.method_6007(class_1308.java:550)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1588.method_6007(class_1588.java:44)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1308.method_5773(class_1308.java:351)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_7260.method_5773(class_7260.java:278)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3218.track(class_3218.java:8754)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3218.redirect$deo000$observable$onTickNonPassenger(class_3218.java:8770)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3218.method_18762(class_3218.java:739)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1937.method_18472(class_1937.java:480)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3218.method_31420(class_3218.java:385)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3218.method_18765(class_3218.java:353)
[08/01/2024 18:08:49 pm] 	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:897)
[08/01/2024 18:08:49 pm] 	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:824)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1132.method_3748(class_1132.java:105)
[08/01/2024 18:08:49 pm] 	at net.minecraft.server.MinecraftServer.handler$zje000$carpet$modifiedRunLoop(MinecraftServer.java:8442)
[08/01/2024 18:08:49 pm] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:650)
[08/01/2024 18:08:49 pm] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:265)
[08/01/2024 18:08:49 pm] 	at java.base/java.lang.Thread.run(Thread.java:833)
[08/01/2024 18:08:49 pm] 
[08/01/2024 18:08:49 pm] 
[08/01/2024 18:08:49 pm] A detailed walkthrough of the error, its code path and all known details is as follows:
[08/01/2024 18:08:49 pm] ---------------------------------------------------------------------------------------
[08/01/2024 18:08:49 pm] 
[08/01/2024 18:08:49 pm] -- Head --
[08/01/2024 18:08:49 pm] Thread: Render thread
[08/01/2024 18:08:49 pm] Stacktrace:
[08/01/2024 18:08:49 pm] 	at java.base/java.util.HashMap$HashIterator.nextNode(HashMap.java:1597)
[08/01/2024 18:08:49 pm] 	at java.base/java.util.HashMap$ValueIterator.next(HashMap.java:1625)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.handler$zze000$alessandrvenchantments$clearStatusEffects(class_1309.java:4645)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.method_6012(class_1309.java)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.method_6095(class_1309.java:1281)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.method_5643(class_1309.java:1217)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1657.method_5643(class_1657.java:928)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3222.method_5643(class_3222.java:732)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_7396.method_43265(class_7396.java:87)
[08/01/2024 18:08:49 pm] 	at java.base/java.util.Optional.ifPresent(Optional.java:178)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_7396.method_43268(class_7396.java:74)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_7396.method_18924(class_7396.java:19)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_4097.method_18923(class_4097.java:66)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_4095.method_19545(class_4095.java:548)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_4095.method_19542(class_4095.java:493)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_7260.method_5958(class_7260.java:311)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1308.method_6023(class_1308.java:788)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.method_6007(class_1309.java:2673)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1308.method_6007(class_1308.java:550)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1588.method_6007(class_1588.java:44)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1309.method_5773(class_1309.java:2419)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1308.method_5773(class_1308.java:351)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_7260.method_5773(class_7260.java:278)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3218.track(class_3218.java:8754)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3218.redirect$deo000$observable$onTickNonPassenger(class_3218.java:8770)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3218.method_18762(class_3218.java:739)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_1937.method_18472(class_1937.java:480)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3218.method_31420(class_3218.java:385)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_5574.method_31791(class_5574.java:54)
[08/01/2024 18:08:49 pm] 	at net.minecraft.class_3218.method_18765(class_3218.java:353)
[08/01/2024 18:08:49 pm] 
[08/01/2024 18:08:49 pm] -- Entity being ticked --
[08/01/2024 18:08:49 pm] Details:
[08/01/2024 18:08:49 pm] 	Entity Type: minecraft:warden (net.minecraft.class_7260)
[08/01/2024 18:08:49 pm] 	Entity ID: 708
[08/01/2024 18:08:49 pm] 	Entity Name: Pancakes
[08/01/2024 18:08:50 pm] Oh no. Minecraft crashed. Please check the logs for any errors and provide these logs when asking for support.```

**Comment by alessandrv** [comment]
After some testing doesn't look like dying with spotter on and the totem of undying causes any crash, also while unlocking the advancement. So I think it may be modpack related.
